# Generated by Django 6.0.2 on 2026-03-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_player_race_alter_skill_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='players', to='db.skill'),
        ),
    ]
